---
stages:
- name: Deploy Marbles Application
  inputs:
  - type: git
    branch: v4.0
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: deploy-marbles-app
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash

      # Test Code
      printf "\n --- Listing services for testing ---\n"
      cf services
      #cf services | sed -n 's/.*\(ibm-blockchain-plan-v1-prod\).*/\1/p'
      printf "\n\nLooking for $SERVICENAME\n"
      cf services | sed -n 's/.*\(${SERVICENAME}\).*/\1/p'

      # Create a service, this is okay to run even if the service already exists, at least as of 01/12/2018
      printf "\n --- Creating an instance of the IBM Blockchain Platform service ---\n"
      cf create-service cloudantNoSQLDB Lite davids-d2b-test

      # Push app (don't start yet, wait for binding)
      printf "\n --- Creating the Marbles application ---\n"
      cf push $CF_APP --no-start

      # Bind app to the blockchain service
      printf "\n --- Binding the IBM Blockchain Platform service to Marbles ---\n"
      cf bind-service $CF_APP davids-d2b-test -c "{\"permissions\":\"read-only\"}"

      # Start her up
      printf "\n --- Starting Marbles ---\n"
      cf start $CF_APP
      #cf restage $CF_APP - this is not needed if we bind before starting

      printf "\n\n --- We are done here. ---\n\n"
