---
stages:
- name: Deploy Marbles Application
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Blue-Green Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash

      # Test Code
      cf services
      #cf services | sed -n 's/.*\(ibm-blockchain-plan-v1-prod\).*/\1/p'
      cf services | sed -n 's/.*\(davids-d2b-test\).*/\1/p'

      # Create a service, this is okay to run even if the service already exists, at least as of 01/12/2018
      cf create-service cloudantNoSQLDB Lite davids-d2b-test

      # Push app (don't start yet, wait for binding)
      cf push $CF_APP --no-start

      # Bind app to the blockchain service
      cf bind-service $CF_APP davids-d2b-test -c "{\"permissions\":\"read-only\"}"

      # Start her up
      cf start $CF_APP
      #cf restage $CF_APP - this is not needed if we bind before starting
